# Generated by Django 3.1.2 on 2020-10-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201009_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='won',
            field=models.BooleanField(default=False),
        ),
    ]
